var eps = angular.module('Eps');
eps.controller('Pacientes', pacientesController);
pacientesController.$inject = ['$scope', '$interval', 'uiGridConstants'];

function pacientesController($scope, $interval, uiGridConstants) {
  var self = this;

  self.gridOptions = {
    enableRowSelection: true,
    enableRowHeaderSelection: false,
    paginationPageSizes: [25, 50, 75],
    paginationPageSize: 25,
    enablePaginationControls: false,
    enableFiltering: false,
    multiSelect: false,
    modifierKeysToMultiSelect: false,
    noUnselect: true,
    onRegisterApi: function(gridApi) {
      self.gridApi = gridApi;
      self.gridApi.grid.registerRowsProcessor(self.singleFilter, 200);
    },
    columnDefs: [
      { field: 'nombre' },
      { field: 'segundoNombre' },
      { field: 'apellidoPaterno' },
      { field: 'documento' },
      { field: 'cumpleaños' },
      { field: 'estadoCivil' },
      { field: 'ciudadOrigen' }
    ]
  };

  self.toggleRowSelection = function() {
    self.gridApi.selection.clearSelectedRows();
    self.gridOptions.enableRowSelection = !self.gridOptions.enableRowSelection;
    self.gridApi.core.notifyDataChange(uiGridConstants.dataChange.OPTIONS);
  };

  self.filter = function() {
    self.gridApi.grid.refresh();
  };

  self.singleFilter = function(renderableRows) {
    var matcher = new RegExp(self.filterValue);
    renderableRows.forEach(function(row) {
      var match = false;
      ['nombre', 'segundoNombre', 'apellidoPaterno'].forEach(function(field) {
        if (row.entity[field].match(matcher)) {
          match = true;
        }
      });
      if (!match) {
        row.visible = false;
      }
    });
    return renderableRows;
  };

  $scope.$watch(function() {
    return self.filterValue;
  }, self.filter);




  var data = [{
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Sergio',
      "segundoNombre": 'Alexander',
      "apellidoPaterno": 'Gutiérrez',
      "apellidoMaterno": 'Bustos',
      "documento": '1016012390',
      "cumpleaños": '18/05/1988',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3138315841',
      "telefono2": '5265086',
      "direccion": 'Cra. 7G 150 25 Apto:401',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Luz',
      "segundoNombre": 'Adriana',
      "apellidoPaterno": 'Remolina',
      "apellidoMaterno": 'Leon',
      "documento": '35124634',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Fabricio',
      "segundoNombre": 'Cristian',
      "apellidoPaterno": 'Rodriguez',
      "apellidoMaterno": 'Rodriguez',
      "documento": '34256544',
      "cumpleaños": '14/09/1990',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '456643',
      "telefono2": '3445646',
      "direccion": '20 de Julio',
      "ciudad": 'Bogotá D.C',
    }, {
      "nombre": 'Pepe',
      "segundoNombre": 'Antonio',
      "apellidoPaterno": 'Perez',
      "apellidoMaterno": 'Peron',
      "documento": '78345237',
      "cumpleaños": '14/09/1986',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '3345315841',
      "telefono2": '234356',
      "direccion": 'Icatá',
      "ciudad": 'Bogotá D.C',
    },
    {
      "nombre": 'Pepito',
      "segundoNombre": 'Toño',
      "apellidoPaterno": 'Perea',
      "apellidoMaterno": 'Leon',
      "documento": '134326678',
      "cumpleaños": '14/09/1952',
      "ciudadOrigen": 'Bogotá D.C',
      "estadoCivil": 'Soltero',
      "telefono1": '2343578',
      "telefono2": '23467',
      "direccion": 'Bosa',
      "ciudad": 'Bogotá D.C',
    },
  ];

  self.gridOptions.data = data;
  $interval(function() { self.gridApi.selection.selectRow(self.gridOptions.data[0]); }, 0, 1);

}